from pytz import NonExistentTimeError


CRYPTO = False
STOCKS = True

class CryptoConfig:

    EXCHANGE = 'binanceus'
    M = 50          # number of assets
    M_BUFFER = 100
    N = 200         # number of trading days
    THRESHOLD = 0.05  # loading threshold
    STABLECOINS = {'USDC/USDT', 'BUSD/USDT', 'TUSD/USDT',
                'USDP/USDT', 'DAI/USDT', 'FDUSD/USDT'}
    CSV_FILE = None

class StockConfig:
    ASSETS = ['SPY', 'QQQ', 'IWM', 'TLT', '^VIX', 'DX-Y.NYB']
    # Union of Appendix A (88 StockCharts indicators) and Table 2 (35 PCA-retained
    # indicators) from Mostafavi & Hooman (2025), Machine Learning with Applications.
    # Each indicator appears once; duplicates from the paper (e.g. Williams AD, VHF)
    # are collapsed to a single entry.
    INDICATORS = {
        "trend": [
            "Candlestick Patterns",
            "Chandelier Exits",
            "Displaced Moving Average",
            "Donchian Channels",
            "Exponential Moving Average",
            "Fibonacci Extensions",
            "Fibonacci Retracements",
            "Fibonacci Weighted Moving Average",
            "Heikin-Ashi Candlesticks",
            "HLC3",
            "Holt-Winters Moving Average",
            "Hull Moving Average",
            "Ichimoku Cloud",
            "Inverted Axis",
            "Kaufman Adaptive Moving Average",
            "KST Indicator",
            "Linear Regression",
            "Linear Regression Indicator",
            "MACD Histogram",
            "MACD Indicator",
            "MACD Percentage",
            "Median Price",
            "Moving Average",
            "Moving Average Filters",
            "Moving Average High/Low/Open",
            "Multiple Moving Averages",
            "Parabolic SAR",
            "Pivot Points",
            "Price Envelope",
            "Rainbow 3D Moving Averages",
            "Simple Moving Average",
            "Symmetric Weighted Moving Average",
            "The Moving Average Oscillator",
            "Trend Lines",
            "Triple Exponential Moving Average",
            "Typical Price",
            "Weighted Close",
            "Weighted Moving Average",
            "Wilder Moving Average",
        ],
        "momentum": [
            "ADX",
            "Aroon Oscillator",
            "Awesome Oscillator",
            "Chande Momentum Oscillator",
            "Choppiness Index",
            "Commodity Channel Index",
            "Compare Prices",
            "Coppock Indicator",
            "Detrended Price Oscillator",
            "Directional Movement",
            "Elder Ray Index",
            "Mass Index",
            "Momentum Indicator",
            "Percentage Price Oscillator",
            "Price Comparison",
            "Price Differential",
            "Price Distance",
            "Price Ratio",
            "Rate of Change (Price)",
            "Relative Strength (Compare)",
            "Relative Strength Index (RSI)",
            "Stochastic Oscillator",
            "Stochastic RSI",
            "TRIX Indicator",
            "True Strength Index",
            "Ultimate Oscillator",
            "Williams %R",
        ],
        "volatility": [
            "ATR Bands",
            "ATR Trailing Stops",
            "Average True Range",
            "Bollinger %B",
            "Bollinger Band® Width",
            "Bollinger Bands",
            "Chaikin Volatility",
            "Keltner Channels",
            "Percentage Bands",
            "Percentage Trailing Stops",
            "Safezone Indicator",
            "Standard Deviation Channels",
            "True Range",
            "Ulcer Index",
            "Vertical Horizontal Filter (VHF)",
            "Volatility",
            "Volatility Ratio",
            "Volatility Stops",
        ],
        "volume": [
            "Accumulation Distribution",
            "Chaikin Money Flow",
            "Chaikin Oscillator",
            "Ease of Movement",
            "Force Index",
            "Money Flow Index",
            "Negative Volume",
            "On Balance Volume",
            "Percentage Volume Oscillator",
            "Positive Volume",
            "Price Volume Trend",
            "Rate of Change (Volume)",
            "Volume",
            "Volume Oscillator",
            "Volume Weighted Average Price",
            "Williams Accumulation Distribution",
        ],
    }

    # Maps human-readable indicator names to TA-Lib function names.
    # None = not available in TA-Lib (requires custom implementation).
    # Tuple values list multiple TA-Lib outputs for multi-line indicators.
    TALIB_MAP = {
        "Accumulation Distribution": "AD",
        "ADX": "ADX",
        "Aroon Oscillator": "AROONOSC",
        "ATR Bands": None,
        "ATR Trailing Stops": None,
        "Average True Range": "ATR",
        "Awesome Oscillator": None,
        "Bollinger %B": None,
        "Bollinger Band® Width": None,
        "Bollinger Bands": "BBANDS",
        "Candlestick Patterns": None,
        "Chaikin Money Flow": None,
        "Chaikin Oscillator": "ADOSC",
        "Chaikin Volatility": None,
        "Chandelier Exits": None,
        "Chande Momentum Oscillator": "CMO",
        "Choppiness Index": None,
        "Commodity Channel Index": "CCI",
        "Compare Prices": None,
        "Coppock Indicator": None,
        "Detrended Price Oscillator": None,
        "Directional Movement": "DX",
        "Displaced Moving Average": None,
        "Donchian Channels": None,
        "Ease of Movement": None,
        "Elder Ray Index": None,
        "Exponential Moving Average": "EMA",
        "Fibonacci Extensions": None,
        "Fibonacci Retracements": None,
        "Fibonacci Weighted Moving Average": None,
        "Force Index": None,
        "Heikin-Ashi Candlesticks": None,
        "HLC3": None,
        "Holt-Winters Moving Average": None,
        "Hull Moving Average": None,
        "Ichimoku Cloud": None,
        "Inverted Axis": None,
        "Kaufman Adaptive Moving Average": "KAMA",
        "Keltner Channels": None,
        "KST Indicator": None,
        "Linear Regression": "LINEARREG",
        "Linear Regression Indicator": "TSF",
        "MACD Histogram": ("MACD", "macdhist"),
        "MACD Indicator": ("MACD", "macd"), 
        "MACD Percentage": "PPO",
        "Mass Index": None,
        "Median Price": "MEDPRICE",
        "Momentum Indicator": "MOM",
        "Money Flow Index": "MFI",
        "Moving Average": "MA",
        "Moving Average Filters": None,
        "Moving Average High/Low/Open": None,
        "Multiple Moving Averages": None,
        "Negative Volume": None,
        "On Balance Volume": "OBV",
        "Parabolic SAR": "SAR",
        "Percentage Bands": None,
        "Percentage Price Oscillator": "PPO",
        "Percentage Trailing Stops": None,
        "Percentage Volume Oscillator": None,
        "Pivot Points": None,
        "Positive Volume": None,
        "Price Comparison": None,
        "Price Differential": "SUB",
        "Price Distance": None,
        "Price Envelope": None,
        "Price Ratio": "DIV",
        "Price Volume Trend": None,
        "Rainbow 3D Moving Averages": None,
        "Rate of Change (Price)": "ROC",
        "Rate of Change (Volume)": None, #("ROC", "volume"),
        "Relative Strength (Compare)": None,
        "Relative Strength Index (RSI)": "RSI",
        "Safezone Indicator": None,
        "Simple Moving Average": "SMA",
        "Standard Deviation Channels": "STDDEV",
        "Stochastic Oscillator": "STOCH",
        "Stochastic RSI": "STOCHRSI",
        "Symmetric Weighted Moving Average": None,
        "The Moving Average Oscillator": "APO",
        "Trend Lines": None,
        "Triple Exponential Moving Average": "TEMA",
        "TRIX Indicator": "TRIX",
        "True Range": "TRANGE",
        "True Strength Index": None,
        "Typical Price": "TYPPRICE",
        "Ultimate Oscillator": "ULTOSC",
        "Ulcer Index": None,
        "Vertical Horizontal Filter (VHF)": None,
        "Volatility": "STDDEV",
        "Volatility Ratio": None,
        "Volatility Stops": None,
        "Volume": None,
        "Volume Oscillator": None,
        "Volume Weighted Average Price": None,
        "Weighted Close": "WCLPRICE",
        "Weighted Moving Average": "WMA",
        "Wilder Moving Average": None,
        "Williams %R": "WILLR",
        "Williams Accumulation Distribution": None,
    }

    INDICATOR_STATUS = {

        'passed_count': 0,
        'failed_count': 0,
        'status_dict': {}

    }