# pytest.ini
[pytest]
# Automatically applies these flags every time you type 'pytest'
addopts = -v --strict-markers

# Tells pytest where to look for test files
pythonpath = .
testpaths = tests


# Custom markers to group tests (e.g., pytest -m smoke)
markers =
    fast: Quick unit tests that take milliseconds.
    slow: Heavy computational tests or deep data transformations.
    pipeline: Tests that run entire processing architecture.
    ta: TA-lib specific test