# pytest.ini
[pytest]
# Automatically applies these flags every time you type 'pytest'
addopts = -v --strict-markers --tb=no

# Tells pytest where to look for test files
pythonpath = .
testpaths = tests


# Custom markers to group tests (e.g., pytest -m smoke)
markers =
    fast: Quick unit tests that take milliseconds.
    slow: Heavy computational tests or deep data transformations.
    pipeline: Tests that run entire processing architecture.
    ta_fast: TA-lib specific test
    ta_slow: TA-lib slow functions
    ta_pipeline: TA-lib processing pipeline
    stock: stock class specific tests